name: "Gilles Lasnier"
description: "Gilles Lasnier's homepage | Distributed Realtime &amp; Embedded Systems"
title: "Gilles Lasnier's homepage | Distributed Realtime &amp; Embedded Systems"
keywords: "Gilles Lasnier, Ciele, ARM, SocFPGA, FPGA, Cyclone, compiler, Altera, Quartus, ISAE, SUPAERO, TELECOM, ParisTech, Telecom-ParisTech, ENST, Ada, Ada95, Ada2005, real-time, distributed, ocarina, polyorb-hi, aadl, behavior, annex, aadlv2, osate2, model, transformation, eclipse, atl, emf, aadl-mt, HLA, certi, ptolemyII, co-simulation, simulation"

blog-name: "Blog"

url: "http://localhost:4000"

paginate: 5
paginate_path: "/blog/page:num/"

markdown: rdiscount
permalink: /blog/:year/:month/:day/:title/
highlighter: pygments

exclude: [Makefile, README, README.md, CNAME]

excerpt_separator: <!--more-->  # the seperator